### ISSUE TITLE
how count total user in channel?

### ISSUE THREAD

**Issue by lordmen99** [AgoraIO/OpenLive-Android#1]
Hi guohai, i have been add count user when join channel its working in screen as broadcaster. but when as audience in the screen cant count realtime. i mean user A broadcaster, then user B,user C,user D,user E join to channel A, total count viewer from user A is 4 viewers. i am stuck here, how count realtime when each user join and leave from channel..?

**Comment by guohai** [comment]
You'd better use your biz server to do the counting
